#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank
    driver-class-name: org.postgresql.Driver
    password: bankpass
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml