server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank
    password: bankpass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
  life-time:
    access: 60m
    refresh: 30m

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/
    url: /v3/api-docs
    configUrl: /v3/api-docs/swagger-config
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
